### ISSUE TITLE
Release new MvvmCross version

### ISSUE THREAD

**Issue by martijn00** [MvvmCross/MvvmCross#1052]
- [x] Determine the next version number (3.5.2 for now) proposals are welcome
- [x] Remove fragging from main repo (pull request #1049)
- [x] Complete examples for Android support
- [x] Update nuspecs to all have the same version
- [x] Update nuspecs to support VS 2015 (https://github.com/MvvmCross/MvvmCross/issues/1082)
- [x] Fix MvvmCross-Forms presenter for Windows
- [ ] Fix Forms examples
- [x] Make sure async DownloadCache works on all platforms
- [x] Write some stuff about the new packes, changes, and more to inform the users
- [x] Add UWP support (https://github.com/MvvmCross/MvvmCross/issues/1009)
- [x] MvvmCross SQLite.Net-PCL wrapper (https://github.com/MvvmCross/MvvmCross/issues/899)
- [x] Roslyn Code Analyzers (https://github.com/MvvmCross/MvvmCross/issues/1040, https://github.com/Stephanvs/MvvmCross.CodeAnalysis)

Skipped: ~~Implement Android Menu inflator to support bindings in menu (https://github.com/MvvmCross/MvvmCross/issues/847)~~

Let me know if i missed something.

**Comment by Cheesebaron** [comment]
Since we are making such big changes to stuff, I suggest we bump the version number.

**Comment by Dexyon** [comment]
I would suggest a version 4.0 indicating that we are actually breaking stuff from 3.X

**Comment by lothrop** [comment]
3.5 was a major breaking change, too, at least for iOS.

**Comment by Cheesebaron** [comment]
I bumped the version to 4.0.0

**Comment by Cheesebaron** [comment]
For the menuinflater stuff, we could maybe get some inspiration from Mugen MVVM: https://github.com/MugenMvvmToolkit/MugenMvvmToolkit/blob/master/Platforms/MugenMvvmToolkit.Android/Binding/Infrastructure/BindableMenuInflater.cs

**Comment by martijn00** [comment]
We should look into the nuget support for VS2015.

Some readings about it.
* http://www.mikeobrien.net/blog/writing-a-nuget-package-for-vs2015-rtm-and-uwp/
* http://oren.codes/2015/07/29/targeting-net-core/
* http://oren.codes/2015/06/16/demystifying-pcls-net-core-dnx-and-uwp-redux/

Issue for it available here: https://github.com/MvvmCross/MvvmCross/issues/1082

**Comment by johnthiriet** [comment]
Is this release (4.0 beta) Material Design compatible ?

**Comment by Cheesebaron** [comment]
Yes

**Comment by johnthiriet** [comment]
Great ! Thanks for the answer. 
For the project I'm working on we have to integrate material design controls from the newest AppCompat. It's nice that we can give it a try now.

**Comment by nunohorta** [comment]
Hi! Do you guys know or have an idea when is it going to be release(v4.0)? Thanks

**Comment by martijn00** [comment]
You could try the beta3 which is quite stable already, but we can't promise a release date.

**Comment by MZetko** [comment]
Seems the new release is just around the corner, with just one open to-do. Is the release expected this year?

**Comment by Cheesebaron** [comment]
Possibly

**Comment by martijn00** [comment]
I think we are almost ready now. Also the new website is ready to launch: https://mvvmcross.readme.io/
It just needs a bit more content.

If anyone want to work on something then the samples can be updated to the latest release.

**Comment by AlanYost** [comment]
Regards an much appreciated

Alan.

**Comment by vvolkgang** [comment]
@martijn00 I've been working on Android with AppCompat and I think we can improve that before shipping. (MvvmCross-AndroidSupport/issues/82)[https://github.com/MvvmCross/MvvmCross-AndroidSupport/issues/82] is simple and would do wonders for a AppCompat sample. What do you think?

**Comment by martijn00** [comment]
@vvolkgang I like the idea! Would you be able to make a PR for that?

**Comment by jonstoneman** [comment]
> If anyone want to work on something then the samples can be updated to the latest release.

@martijn00 I'll try to find the time to look at the TipCalc sample and the docs over the next week or so.

**Comment by lothrop** [comment]
@jonstoneman I did the iOS TipCalc sample doc today. The other platforms are still old versions.

**Comment by martijn00** [comment]
Ideally all the old samples are updated to 4.0 too because users still look at them for help.
