### ISSUE TITLE
Website issues/features

### ISSUE THREAD

**Issue by MarcBruins** [MvvmCross/MvvmCross#1727]
There are still some features that need to be implemented for the website and some bugs to fix. This is a collection of the those issues and features which should be resolved.

Remaining:

- [x] Header image should have bigger height
- [x]  Add better styling to OpenCollective
- [ ]  Newsletter

Features:
- [x]  Branding page

Desktop:
- [x]  Add opencollective widget to website(https://github.com/OpenCollective/OpenCollective/wiki/Website-widget) #1723
- [x]  Give Get Started button on landing page a hover effect #1800
- [x]  Order TipCalc tutorial pages #1772 
- [x] Enable google analytics #1771 
- [x]  Clickable headers in documentation [63674fd](https://github.com/MvvmCross/MvvmCross/commit/63674fd2729fd82b6bd155e29aa24dab5f702216)
- [x]  Header logo is blurry

Mobile:
- [x]  Space between the logo images #1800
- [x]  Search positioning is incorrect and it doesn't display the icon #1802
- [x]  Hamburger icon flies to the left side once clicked #1802
- [x]  Documentation menu is to small #1776
- [x]  Search field has no bottom margin
- [x]  Search field can be fully opened by default on mobile

Note that website is based on github-pages and jekyll. If you would like to help out resolving those issues just fork the mvvmcross repo and enable [github-pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for your fork. After that you can edit the website in your own repository and make a PR when ready.

**Comment by CayasSoftware** [comment]
Wouldn't it be better to extract the website into it's own repository? I think it makes it easier for contributions.

**Comment by MarcBruins** [comment]
Why? Now you can make your PR and fix a bug or add functionality and make docs changes about what you have done at the same time. No need to make two pull request on two different repos. I can add a howto guide for contributing to the website if that helps?

**Comment by CayasSoftware** [comment]
Just a thought. A different repo brings different issue tracking, which I would prefer for the reason that a website issue is not a framework issue. But I see your the point here.

**Comment by MarcBruins** [comment]
I agree that it would be nice if the website issues didn't clutter up the issue tracking of the main framework. Because this is a new website that has just launched there are a little bit more issues then there would be once the website is more mature(after fixing the above issues for ex). Sure there would be some changes to it now and then but that should stick with only a few. It's most important purpose is to make it easy for developers to add or edit docs about the changes they did to the framework so that we have great documentation in the end!

**Comment by Cheesebaron** [comment]
The MvvmCross logo on the docs site looks blurry on my mac. Seems like the super large image scaled down becomes blurry. Not sure if we maybe could help this issue by using SVG in modern browsers.

**Comment by martijn00** [comment]
With https://github.com/MvvmCross/MvvmCross/pull/1852 most issue's are fixed.

**Comment by martijn00** [comment]
Let's create separate issue's for Website tasks from now on.
