### ISSUE TITLE
🧾 Improve documentation

### ISSUE THREAD

**Issue by Cheesebaron** [MvvmCross/MvvmCross#4051]
People have been telling us that the documentation is not up to date or lacking. I would like to track enhancements and improvements in this issue.

Here is a list of areas that could use improvement:
- [ ] List of packages is outdated: https://www.mvvmcross.com/documentation/getting-started/mvvmcross-packages
- [ ] View Presenters pages doesn't seem to cover all aspects of the presenter https://www.mvvmcross.com/documentation/fundamentals/view-presenters
  - [ ] `IMvxOverridePresentationAttribute` you have to drill into the platform specific documentation to find this information
  - [ ] Provide better indexing of platform specifics, it is not easy to find in the index on the left (perhaps even switch to a different website generator to solve this)
  - [ ] Hints with support matrix #3402
 - [ ] About page is blank #3863 
 - [ ] Update `MvxMessenger` documentation to describe gotchas about GC and tokens #3242
 - [ ] Ensure Getting Started documentation is easy to follow. Perhaps make a small repo with a project that contains a good starting point and document it #2857
 - [ ] Finnish documentation for essential controls #2631

If something is missing in this thread, please add a new comment and description. I will create separate issues for each of the listed areas

**Comment by Cheesebaron** [comment]
@Hackmodford here is a list of areas we could improve in the documentation. All help is appreciated 🙏

**Comment by Hackmodford** [comment]
If memory serves right, there is some missing information regarding using Storyboards
https://www.mvvmcross.com/documentation/platform/ios/ios-user-interfaces-approaches?scroll=406

Something about having the storyboard id set properly so MvvmCross can find the view.

**Comment by Hackmodford** [comment]
I also feel like there's some singletons that are missing in the documentation. For example `IMvxAndroidCurrentTopActivity`.

**Comment by Hackmodford** [comment]
I feel confident I could tackle #2857 since I have done this multiple times at this point.

**Comment by Cheesebaron** [comment]
You are welcome to take a stab at #2857. I would probably add a good getting started project in the MvvmCross-Samples repo for that one.

**Comment by Hackmodford** [comment]
Any thoughts on using MvxScaffolding for #2857? It seems like it's the quickest way to get a decent project up and running. The guide could then be more about what the various pieces and base classes are used for.

**Comment by Cheesebaron** [comment]
@Hackmodford MvxScaffolding is good. I'd be fine with having that as an example. @Plac3hold3r would you be OK with us using that as an example in the MvvmCross docs?

**Comment by Plac3hold3r** [comment]
@Cheesebaron and @Hackmodford no issue, my side, feel free to use it as you like. Just a note MvxScaffolding only has a UI for Visual Studio on windows. There is the CLI option which is cross-platform. 

The Visual Studio team is also busy integration dotnet templates directly into the UI's for both Mac and Windows. So, the experience will change once the feature leaves preview.

**Comment by Hackmodford** [comment]
I think the best approach is to use the commandline version of MvxScaffolding to ensure the guide works for everyone.

@Cheesebaron [Here's](https://github.com/Hackmodford/MvvmCross/blob/patch-7/docs/_documentation/getting-started/getting-started.md) a rough draft of a proposed change to getting started. After stealing the instructions from @Plac3hold3r the page now has everything needed to create a blank project and naturally leads into either reading more documentation or following the tip calculator tutorial.

The next change I would propose is to modify the tip calculator tutorial to use MvxScaffolding to create the project. This would be instead of creating a "getting started" sample project. Any thoughts on this?

**Comment by Hackmodford** [comment]
- [ ] Brandin page is blank #4056

**Comment by Cheesebaron** [comment]
Added to the list :)

**Comment by Hackmodford** [comment]
@Cheesebaron Any thoughts on my getting started page?
If you approve should I also edit the tip calculator project? Or do that in a different pr?

**Comment by Hackmodford** [comment]
The [Custom Data Binding docs](https://www.mvvmcross.com/documentation/advanced/custom-data-binding) could use a section on FillBindingNames. I had to figure out the hard way why my custom target binding wasn't working without using `For()`.

This was the key

```C#
protected override void FillBindingNames(IMvxBindingNameRegistry registry)
{
    base.FillBindingNames(registry);
            
    registry.AddOrOverwrite(typeof(MaterialComponents.TextInputControllerOutlined), "ErrorText");
}
```
